### ISSUE TITLE
Politikredse - manglede søgeresultat

### ISSUE THREAD

**Issue by AmandaWS** [Dataforsyningen/gsearch#57]
Hvis jeg søger på `"vest" `får jeg ikke noget resultat frem.
https://gsearch.k8s-test-121.septima.dk/geosearch?search=Vest&resources=politikreds&limit=20

<img width="950" alt="Skærmbillede 2022-01-24 kl  12 38 56" src="https://user-images.githubusercontent.com/32768813/150776432-e98ad07f-7d77-4b89-beb3-dbeb3d6981ed.png">

Hvis jeg søger på "veste" kommer 1 resultat fram:

`"Københavns Vestegns Politikreds"`

------------

I Widget får disse når jeg søger på `"vest"`:
<img width="418" alt="Skærmbillede 2022-01-24 kl  12 35 13" src="https://user-images.githubusercontent.com/32768813/150776372-df4687bc-5eb8-4833-bca1-e51776f2d93a.png">

**Comment by Aramos93** [comment]
Er det ikke fordi du skal folde "data" fanen ud? der er en lille pil til venstre

**Comment by AmandaWS** [comment]
jo da! Er det når der kommer flere end 2 resultater??

**Comment by Aramos93** [comment]
Efter et hvis antal ja, det virker godt nok dumt den gør det med 3. Det er noget firefox optimering, så den ikke åbner al data hvis nu den returnerer tusind
