### ISSUE TITLE
søgning på Sogne giver for få resultater

### ISSUE THREAD

**Issue by AmandaWS** [Dataforsyningen/gsearch#59]
Ved søgning på "nørre" kommer der 31 resultater. I widget kommer der 33 resultater.

Jeg aner dog ikke hvilket resultat der er korrekt 🙃

https://gsearch.k8s-test-121.septima.dk/geosearch?search=n%C3%B8rre&resources=sogn&limit=50

<img width="876" alt="Skærmbillede 2022-01-24 kl  22 28 22" src="https://user-images.githubusercontent.com/32768813/150867872-e3785bf3-a513-454f-bfee-d3a205bdc16b.png">

https://septima.dk/widget/examples/search11.html

<img width="592" alt="Skærmbillede 2022-01-24 kl  22 26 43" src="https://user-images.githubusercontent.com/32768813/150867633-13cb27cb-a343-441b-95ce-c862016ffec5.png">

**Comment by AnetteKlinker** [comment]
Nørre Galten sogn og Nørre Vedby sogn er historiske og burde vel ikke komme med i svar i widget .

**Comment by cfischer00** [comment]
Vi viser kun aktuelle sogne
