### ISSUE TITLE
AA og Å giver ikke samme resultater

### ISSUE THREAD

**Issue by AmandaWS** [Dataforsyningen/gsearch#60]
Hvis jeg søger på "aarhus 3" kommer der 41 hits:
https://gsearch.k8s-test-121.septima.dk/geosearch?search=aarhus%203&resources=adresse&limit=100

men hvis jeg søger på "århus 3" kommer der 59 hits:
https://gsearch.k8s-test-121.septima.dk/geosearch?search=%C3%A5rhus%203&resources=adresse&limit=100

**Comment by cfischer00** [comment]
Det er rettet
